name: dservers
description: Dart server side framework. For easy setup backend servers in dart.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:

dev_dependencies:


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #